import { useEffect } from "react";

const FetchOptions = ({ setSpecialties, setCities }) => {
  useEffect(() => {
    // Static data for specialties and cities
    const specialties = [
      "Cardiology",
      "Pediatrics",
      "Orthopedics",
      "Dermatology",
      "Neurology",
      "Gastroenterology",
      "Hematology",
      "Oncology",
      "Endocrinology",
      "Rheumatology",
      "Pulmonology",
      "Urology",
      "Nephrology",
      "Ophthalmology",
      "Otolaryngology",
      "Psychiatry",
      "Radiology",
      "Anesthesiology",
      "Pathology",
      "General Surgery",
      "Plastic Surgery",
      "Thoracic Surgery",
      "Vascular Surgery",
      "Emergency Medicine",
      "Family Medicine",
      "Internal Medicine",
      "Infectious Disease",
      "Obstetrics & Gynecology",
      "Pediatrics",
      "Sports Medicine",
      "Geriatrics",
      "Immunology",
      "Allergy",
      "Physical Medicine & Rehabilitation",
      "Pain Management",
      "Neonatology",
      "Otorhinolaryngology",
      "Dentist",
      "Orthodontics",
      "Cosmetic Dentistry",
      "Endodontics",
      "Prosthetics & Orthotics",
      "Oral Surgery",
      "Periodontics",
      "Prosthodontics",
      "Maxillofacial Surgery",
      "Prosthodontics",
      "Prosthodontics",
      "Prosthodontics",
      "Prosthodontics",
    ];

    const cities = [
      "Dehra Dun",
      "Delhi",
      "Mumbai",
      "Bangalore",
      "Chennai",
      "Meerut",
      "Kolkata",
      "Hyderabad",
      "Pune",
      "Ahmedabad",
      "Jaipur",
      "Surat",
      "Lucknow",
      "Kanpur",
      "Nagpur",
      "Visakhapatnam",
      "Indore",
      "Thane",
      "Bhopal",
      "Patna",
      "Vadodara",
      "Ghaziabad",
      "Ludhiana",
      "Agra",
      "Nashik",
      "Faridabad",
      "Meerut",
      "Rajkot",
      "Kalyan-Dombivli",
      "Vasai-Virar",
      "Varanasi",
      "Srinagar",
      "Aurangabad",
      "Dhanbad",
      "Amritsar",
      "Navi Mumbai",
      "Allahabad",
      "Ranchi",
      "Howrah",
      "Coimbatore",
      "Jabalpur",
      "Gwalior",
      "Vijayawada",
      "Jodhpur",
      "Madurai",
      "Raipur",
      "Kota",
      "Chandigarh",
      "Guwahati",
      "Solapur",
      "Hubli-Dharwad",
      "Mysore",
      "Tiruchirappalli",
      "Bareilly",
      "Aligarh",
      "Tiruppur",
      "Moradabad",
      "Jalandhar",
      "Bhubaneswar",
      "Salem",
      "Warangal",
      "Guntur",
      "Bhiwandi",
      "Saharanpur",
      "Gorakhpur",
      "Bikaner",
      "Amravati",
      "Noida",
      "Jamshedpur",
      "Bhilai",
      "Cuttack",
      "Firozabad",
      "Kochi",
      "Nellore",
      "Bhavnagar",
      "Dehradun",
      "Durgapur",
      "Asansol",
      "Rourkela",
      "Nanded",
      "Kolhapur",
      "Ajmer",
      "Gulbarga",
      "Jamnagar",
      "Ujjain",
      "Loni",
      "Siliguri",
      "Jhansi",
      "Ulhasnagar",
      "Nellore",
      "Jammu",
      "Sangli-Miraj & Kupwad",
      "Mangalore",
      "Erode",
      "Belgaum",
      "Ambattur",
      "Tirunelveli",
      "Malegaon",
      "Gaya",
      "Udaipur",
      "Maheshtala",
      "Davanagere",
      "Kozhikode",
      "Akola",
      "Kurnool",
      "Rajpur Sonarpur",
      "Bokaro Steel City",
      "South Dumdum",
      "Bellary",
      "Patiala",
      "Gopalpur",
      "Agartala",
      "Bhagalpur",
      "Muzaffarnagar",
      "Bhatpara",
      "Panihati",
      "Latur",
      "Dhule",
      "Rohtak",
      "Korba",
      "Bhilwara",
      "Brahmapur",
      "Muzaffarpur",
      "Ahmednagar",
      "Mathura",
      "Kollam",
      "Avadi",
      "Kadapa",
      "Anantapur",
      "Kamarhati",
      "Bilaspur",
      "Sikar",
      "Serampore",
      "Adoni",
      "Kharagpur",
      "Agra",
      "Nagpur",
      "Jalgaon",
      "Udaipur",
      "Davangere",
      "Asansol",
      "Bardhaman",
      "Kamarhati",
      "Nadiad",
      "Sambalpur",
      "Secunderabad",
    ];

    // Set the specialties and cities using the provided setter functions
    setSpecialties(specialties);
    setCities(cities);
  }, [setSpecialties, setCities]);

  return null;
};

export default FetchOptions;
